/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Emotion = IDL.Variant({
  'sad' : IDL.Null,
  'tired' : IDL.Null,
  'anxious' : IDL.Null,
  'happy' : IDL.Null,
  'focused' : IDL.Null,
  'calm' : IDL.Null,
  'stressed' : IDL.Null,
  'motivated' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MoodLog = IDL.Record({
  'emotion' : Emotion,
  'timestamp' : IDL.Int,
});
export const StudySession = IDL.Record({
  'subject' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'startEmotion' : Emotion,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createStudySession' : IDL.Func([IDL.Text, Emotion, IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodLog)], ['query']),
  'getStudyHistory' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getStudyRecommendations' : IDL.Func(
      [Emotion],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeRecommendations' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logMood' : IDL.Func([Emotion], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Emotion = IDL.Variant({
    'sad' : IDL.Null,
    'tired' : IDL.Null,
    'anxious' : IDL.Null,
    'happy' : IDL.Null,
    'focused' : IDL.Null,
    'calm' : IDL.Null,
    'stressed' : IDL.Null,
    'motivated' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MoodLog = IDL.Record({ 'emotion' : Emotion, 'timestamp' : IDL.Int });
  const StudySession = IDL.Record({
    'subject' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'startEmotion' : Emotion,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createStudySession' : IDL.Func([IDL.Text, Emotion, IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMoodHistory' : IDL.Func([], [IDL.Vec(MoodLog)], ['query']),
    'getStudyHistory' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getStudyRecommendations' : IDL.Func(
        [Emotion],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeRecommendations' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logMood' : IDL.Func([Emotion], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };