/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Emotion = { 'sad' : null } |
  { 'tired' : null } |
  { 'anxious' : null } |
  { 'happy' : null } |
  { 'focused' : null } |
  { 'calm' : null } |
  { 'stressed' : null } |
  { 'motivated' : null };
export interface MoodLog { 'emotion' : Emotion, 'timestamp' : bigint }
export interface StudySession {
  'subject' : string,
  'durationMinutes' : bigint,
  'startEmotion' : Emotion,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createStudySession' : ActorMethod<[string, Emotion, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMoodHistory' : ActorMethod<[], Array<MoodLog>>,
  'getStudyHistory' : ActorMethod<[], Array<StudySession>>,
  'getStudyRecommendations' : ActorMethod<[Emotion], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeRecommendations' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logMood' : ActorMethod<[Emotion], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];